#!/bin/bash -x

# 1. Clone source from https://github.com/awslabs/amazon-kinesis-agent.git
# 2. Run the setup script to build
#    sudo ./setup --build
# 3. Will likely fail due to java version, manually install openjdk-11-jdk-headless
# 4. run sudo update-alternatives --config java and select java 8
# 5. Uninstall any version of java you do not want
# 3. Run this make-debian script to create .deb

if [ $# -ne 2 ]; then
    echo "Usage: <$0> <compilation dir> <version>"
fi

COMPILE_DIR=$1
VERSION=$2


if [[ -f /etc/lsb-release ]]; then
    DIST=Ubuntu
elif [[ -f /etc/debian_version ]]; then
    DIST=Debian
fi

if [[ ! -d "$COMPILE_DIR" ]]; then
    echo "ERROR: Unable to find compile dir"
    exit 1

fi

if [[ ! -f "$COMPILE_DIR/setup" ]]; then
    echo "ERROR: setup script not found, check compile dir"
    exit 1
fi

if [[ "$(arch)" != "x86_64" ]]; then
    echo "ERROR: Unexpected architecutre 64 bit x86 expected"
    exit 1
fi

echo "Creating working dir structure"

DAEMON=aws-kinesis-agent
AGENT_USER=aws-kinesis-agent-user
WORK_DIR=work/${DAEMON}_${VERSION}-${DIST}_amd64
BIN_DIR=usr/bin
JAR_DIR=/usr/share/${DAEMON}/lib

mkdir -p ${WORK_DIR}
mkdir -p ${WORK_DIR}/etc/aws-kinesis
mkdir -p ${WORK_DIR}/etc/cron.d
mkdir -p ${WORK_DIR}/etc/default
mkdir -p ${WORK_DIR}/etc/init.d
mkdir -p ${WORK_DIR}/etc/aws-kinesis/agent.d
mkdir -p ${WORK_DIR}/usr/
mkdir -p ${WORK_DIR}/usr/bin
mkdir -p ${WORK_DIR}/${JAR_DIR}
mkdir -p ${WORK_DIR}/var/log/${DAEMON}
mkdir -p ${WORK_DIR}/var/run/${DAEMON}

install -m755 ${COMPILE_DIR}/bin/start-${DAEMON} ${WORK_DIR}/${BIN_DIR}
install -m755 ${COMPILE_DIR}/bin/${DAEMON}-babysit ${WORK_DIR}/${BIN_DIR}
install -m644 ${COMPILE_DIR}/dependencies/* ${WORK_DIR}/${JAR_DIR}
install -m644 ${COMPILE_DIR}/ant_build/lib/* ${WORK_DIR}/${JAR_DIR}
install -m755 ${COMPILE_DIR}/bin/${DAEMON}.${DIST} ${WORK_DIR}/etc/init.d/${DAEMON}
install -m644 ${COMPILE_DIR}/support/${DAEMON}.cron ${WORK_DIR}/etc/cron.d/${DAEMON}
install -m644 ${COMPILE_DIR}/support/${DAEMON}.sysconfig ${WORK_DIR}/etc/default/${DAEMON}
install -m644 ${COMPILE_DIR}/support/log4j.xml ${WORK_DIR}/etc/aws-kinesis
install -m644 ${COMPILE_DIR}/configuration/release/aws-kinesis-agent.json ${WORK_DIR}/etc/aws-kinesis/agent.json

echo "Creating DEBIAN structure"
mkdir -p ${WORK_DIR}/DEBIAN

# Setup deb control
cat << EOF > ${WORK_DIR}/DEBIAN/control
Package: ${DAEMON}
Version: ${VERSION}
Architecture: amd64
Maintainer: Silverstripe Platform <theserverpeople@silverstripe.com>
Description: Platform package to ship monitored logs to kinesis.
 Used currently to get logs sent to Logrhythm via kinesis stream through firehose to S3.
Depends: default-jre-headless | java6-runtime-headless
Recommends: rsyslog
EOF

# Setup deb postinst
cat << EOF > ${WORK_DIR}/DEBIAN/postinst
#!/bin/sh

set -e

# On a fresh install, add the necessary user and group
if ! getent passwd ${AGENT_USER}; then
    adduser --quiet --system --no-create-home --home /etc/aws-kinesis --group --disabled-password ${AGENT_USER} || true
fi

if ! id -nG ${AGENT_USER} | grep -qw syslog; then
    # Put user kinesis user in group syslog, so the daemon can read files owned by group
    adduser --quiet ${AGENT_USER} syslog
fi

# Set up /var/run dir for checkpoints
if [ ! -d /var/run/${DAEMON} ]; then
    mkdir /var/run/${DAEMON}
fi

chown ${AGENT_USER} /var/run/${DAEMON}
chgrp ${AGENT_USER} /var/run/${DAEMON}
chmod 0755 /var/run/${DAEMON}

# Set up daemon dir
if [ ! -d /var/log/${DAEMON} ]; then
    mkdir /var/log/${DAEMON}
fi

chown ${AGENT_USER} /var/log/${DAEMON}
chgrp ${AGENT_USER} /var/log/${DAEMON}
chmod 0755 /var/log/${DAEMON}

# Restart and enable service
/bin/systemctl daemon-reload
/bin/systemctl restart aws-kinesis-agent
/bin/systemctl enable aws-kinesis-agent

exit 0
EOF
chmod 0755 ${WORK_DIR}/DEBIAN/postinst

# Build package
dpkg-deb --build --root-owner-group ${WORK_DIR}
